services:
  - type: web
    name: google-business-scraper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: ZAPIER_WEBHOOK_URL
        value: https://webhook.site/your-unique-url
        sync: false 